% this is a simplified version of 
% https://github.com/yihui/knitr/blob/master/inst/examples/knitr-beamer.Rnw
\documentclass{beamer}
\begin{document}
<<setup, include=FALSE>>=
# smaller font size for chunks
opts_chunk$set(size = 'footnotesize')
@
\title{Introducci\'on a la Gen\'omica \\ UNAL nov 2017}
\author{Alejandro Caceres \\ ISGlobal, Barcelona}


\maketitle

% very important to use option [fragile] for frames containing code output!

\begin{frame}[fragile]
\frametitle{Control de Calidad}
Los datos de microarrays son sometidos un control de calidad
\begin{itemize}

\item {\tt SNPs}: Calidad del genotipado o que biol\'ogimcamente no correspondan a lo esperado 

\item {\tt Sujetos}: Sujetos que son ''outliers´´ de la muestra: ancestr\'ia o parentesco 

\end{itemize}
\end{frame}

\begin{frame}[fragile]
\frametitle{Genotipado}
En illumina los datos crudos son las intensidades de cada alelo

\begin{figure}[htbp]
\begin{center}
\includegraphics[height=3cm,with=3cm]{clustermicro.jpg}
\end{center}
\end{figure}

entre menos varianza en angulo entre los grupos mejor es la genotipacion del SNP

\begin{itemize}[fragile]
\item B-allelefreq: la intensidad relativa del allelo B respecto al A (angulo)
\item log2ratio: la intensidad de la observacion respecto al grupo (magnitud)
\end{itemize}

\end{frame}



\begin{frame}[fragile]
\frametitle{GenomeStudio}

Es el software de Illumina para hacer el genotipado de los SNPs (clustering)
\begin{figure}[htbp]
\begin{center}
\includegraphics[height=3cm,with=3cm]{genomestudio.jpg}
\end{center}
\end{figure}

\begin{itemize}
\item el control de calidad en el genotiupado est\'a dado por el clustering
\item reporta un calldate y un valor del numero de sujetos con genotipado aceptable por SNP 
\item genera los genotipos en formato PLINK 
\end{itemize}

\end{frame}


\begin{frame}[fragile]
\frametitle{Control de Sujetos}

\begin{itemize}
\item que el sexo es el reportado o detecc\ion de aneploidías como XXY, XYY, etc 
\item cosanginidad mas alta de la esperado en el diseño del estudio 
\end{itemize}

\end{frame}


\begin{frame}[fragile]
\frametitle{Identidad por desCendencia}

La consanginidad (identity by descent) se puede calcular en PLINK por medio de la opci\'on --genome

\begin{verbatim}
acaceres@IMW00680:~$ plink --bfile [filename prefix] --genome 
\end{verbatim}

y produce un reporte en el fichero {\tt plink.genome}
\end{frame}


\begin{frame}[fragile]
\frametitle{Control de Sujetos}

\begin{itemize}
\item que el sexo es el reportado o detecc\ion de aneploidías como XXY, XYY, etc 
\item cosanginidad mas alta de la esperado en el diseño del estudio 
\end{itemize}

\end{frame}


\begin{frame}[fragile]
\frametitle{Control de calidad de SNPs}

\begin{itemize}
\item Call-rate (dada por genomeStudio): $>80\%$
\item Minor allele frequency (MAF): $>0.01$ o $>0.05$
\item Hardy Weinberg Equillibrium: menos de 3 o 4 desviaciones standard 
\item Mendelian errors: si hay trios que no tengan errores de trasmisi\'on
\end{itemize}

\end{frame}

\begin{frame}[fragile]
\frametitle{Equilibrio de Hardy Weinberg}

En una poblaci\'on en donde no hay fuerzas que cambien la frecuencia alelica $p$ (de un SNP)
debemos encontar
\begin{itemize}
\item $p^2$ fracci\'on de homicigotos
\item $2*p*(p-1)$ fracci\'on de heretocigotos
\item $(1-p)^2$ fracci\'on de homocigotos variantes
\end{itemize}

que se deducen por la asociaci\'on aleatoria entre los cromosomas paternos y maternos


\end{frame}



\begin{frame}[fragile]
\frametitle{Equilibrio de Hardy Weinberg}

SNPs que no est\'an en WHE pueden presentar

\begin{itemize}
\item Problemas de genotipaci\'on. Por ejemplo una sonda defectuosa en la mitad de la población (Alta disviaci\'on-Probable).
\item Fuerzas evolutivas sobre el SNP (Baja disviaci\'on-Menons probable)).
\end{itemize}

Si la desviación en biol\'ogica como en el segundo caso, SNPs vacinos que estan en LD tambi\'en deben estar desviados. 

\end{frame}

\begin{frame}[fragile]
\frametitle{Errores Mendelianos}
Para un estudio con trios los SNPs de 
\begin{itemize}
\item dos padres homocigotos para el mismo alelo no pueden tener un hijo que no sea homocigoto
\item un padre homocigoto y una madre heterocigota no pueden tener un hijo que no sea homocigoto alternativo
\item un padre homocigoto para un alelo y una madre homocigota para el otro alele no pueden tener un hijo homocigoto para ning\'un alelo 
\end{itemize}

desviaciones en estas reglas son herrores de trasmisi\'on mendelianos e indican error en genotipaci\'on

\end{frame}



\begin{frame}[fragile]
\frametitle{Software}

\begin{itemize}
\item el control de calidad para MAF, HWE y call-rate se puede hacer con la mayor\'ia de paquertes
\item veamos como se have con SNPstats
\end{itemize}

En R cargemos la librer\'ia y los datos
<<eval>>=
library("snpStats")
load("snpsSNPstats.RData")
snpsSNPstats
@
\end{frame}


\begin{frame}[fragile]
\frametitle{SNPStats}
{\tt col.summary} calcula call-rate, MAF, HWE para todos los SNPs en la base de datos
<<>>=
sum <- col.summary(snpsSNPstats)
dim(sum)
head(sum)
@
\end{frame}

\begin{frame}[fragile]
\frametitle{SNPStats}
obtengamos los SNPs con call-rate >0.8
<<>>=
Callrate <- sum$Call.rate
selectCallRate <- Callrate > 0.8
length(selectCallRate)
head(selectCallRate)
@
\end{frame}


\begin{frame}[fragile]
\frametitle{SNPStats}
obtengamos los SNPs con frequencia mayor a 0.01
<<>>=
MAF <- sum$MAF
selectMAF <- MAF > 0.01
length(selectMAF)
head(selectMAF)
@

\begin{frame}[fragile]
\frametitle{SNPStats}
Cuales SNPs tienen $MAF>0.01$ y $CallRate > 0.80$
<<>>=
selectMAFCAllrete <- selectMAF & selectCallRate
head(selectMAFCAllrete)
table(selectMAFCAllrete)
@

<<>>=
snpnames <- colnames(snpsSNPstats)
length(snpnames)
head(snpnames)
selsnpnames <- snpnames[selectMAFCAllrete]
length(selsnpnames)
head(selsnpnames)
@


\begin{frame}[fragile]
\frametitle{SNPStats}
teniendo los SNPs se puede seleccionar una submatriz de los genotipos con s\'olo estos SNPs
<<>>=
NewsnpsSNPstats<-snpsSNPstats[,selsnpnames]
NewsnpsSNPstats
@


\end{frame}


\begin{frame}[fragile]
\frametitle{Ejercicio}

\begin{itemize}
\item Seleccionar ahora los SNPs que tienen $abs(sum\$z.HWE) < 6$
\item Crear una nueva matriz con los SNPs seleccionados
\end{itemize}

desviaciones en estas reglas son herrores de trasmisi\'on mendelianos e indican error en genotipaci\'on

\end{frame}

\begin{frame}[fragile]
\frametitle{ejercicio}
<<>>=
selhw<-abs(sum$z.HWE) < 6
NewsnpsSNPstats<-snpsSNPstats[, selhw & selectMAF & selectCallRate]
save(NewsnpsSNPstats, file="NewsnpsSNPstats.RData")
@


\end{frame}




\end{document}